spring:

  application:
    name: ad_dashboard

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ad_dashboard
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  config:
    import: optional:file:.env[.properties]

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql

meta:
  api:
    ad-account-id: ${META_AD_ACCOUNT_ID}
    access-token: ${META_ACCESS_TOKEN}

sync:
  cron:
    yesterday: "0 0 10 * * *"
    seven-days: "0 0 16 * * *"
